import "../scss/globals.scss";

export const metadata = {
  title: "Last Fm",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body>{children}</body>
    </html>
  );
}
